# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

title: Murilo Holanda
description: "Personal site"
url: https://murilolh.github.io
repo: https://github.com/murilolh
baseurl: ""

# Author settings
author:
  name: Murilo Holanda
  job: Software Developer
  bio: "BSc in Computer Science, IT Professional with over 7 years of experience in development, migration, innovation, research, deployment and maintenance projects."
  thumb: /images/author.jpg
  email: mailto:murilolh@gmail.com
  url: https://murilolh.github.io/
  github: https://github.com/murilolh
  linkedin: https://linkedin.com/in/murilolh

# navbar pages
navbar:
  - slug: about
    title: About

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json", "Rakefile"]
